Convert src/js** to TypeScript
vivliostyle/vivliostyle-ui pull request #79
Opened 2019-10-04 14:40 UTC by kubosho

## Abstract

TBA

## Motivation

Increase interoperability with static typing world like TypeScript or Flowtype.

## Detailed Design

### Added new build system

TBA

### Convert to TypeScript

TBA

## Drawback

TBA

## Unresolved Items

2019-10-04 14:56 UTC, kubosho commented
I still have to make corrections the test files.
Then, this PR is many changes. I want to write the PR description properly.
Therefore using Draft.

2019-10-17 16:00 UTC, kubosho commented
@MurakamiShinyu could you review this?

2019-10-19 14:06 UTC, MurakamiShinyu requested changes

2019-10-19 14:06 UTC, MurakamiShinyu commented on src/html/vivliostyle-viewer.ejs
> +<script src="js/vivliostyle-ui.js"></script>
"js/vivliostyle-ui.js" should be "js/vivliostyle-ui.min.js"

2019-10-20 05:45 UTC, MurakamiShinyu commented on webpack.config.js
> +                NODE_ENV: JSON.stringify(process.env.NODE_ENV !== "production")
`NODE_ENV: JSON.stringify(process.env.NODE_ENV !== "production")` should be
`NODE_ENV: JSON.stringify(process.env.NODE_ENV")` ?

2019-10-22 07:54 UTC, kubosho commented
@MurakamiShinyu Could you review this?

2019-10-22 10:03 UTC, MurakamiShinyu approved these changes

2019-10-22 10:04 UTC, MurakamiShinyu commented
@kubosho Thanks, LGTM!

BTW, we decided to use Prettier default (such as 2space indent) as I wrote in our slack https://vivliostyle.slack.com/archives/CNN5GPF9V/p1570589074067100.
The code format change can be done with another pull request, but also it will be good to include the change (remove `.prettierrc.js` and do `prettier --write`) in this pull request, because it makes sense to start with the new code format for the new TypeScript code. How about it?

2019-10-22 12:54 UTC, kubosho commented
I will send Pull Request to follow up this Pull Request,

2019-10-22 12:54 UTC, merged

2019-11-25 10:08 UTC, MurakamiShinyu commented
Found regressions and fixed:
- https://github.com/vivliostyle/vivliostyle-ui/commit/e4bb42224220854470529ef32982adcd32c4c22e
- https://github.com/vivliostyle/vivliostyle-ui/commit/9ee7cc9ae5046d9226a92b528f48e2ce20ec7ce5